### PR TITLE
feat: update jambonz-ui:0.0.20

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by davehorton** [comment]
```
No matching version found for jambonz-ui@^0.0.20.
```
dependency should now be @jambonz/ui-kit

**Comment by xquanluu** [comment]
chainging now

**Comment by davehorton** [comment]
tests still failing so keep at it

**Comment by xquanluu** [comment]
Hi @davehorton it seem that the Jambonz/ui-kit was not successfully build and upload the artifact.

When next-static-site build, npm install download @jambon/ui-kit with wrong file withhout dist folder, that import is not working for next-static-site.

Can you help to double check this.

For now I manually rebuild ui-kit locally and it's working

**Review by davehorton — APPROVED** [review]

**Pull request merged**
