### PR TITLE
add navi link for blog

### PR DESCRIPTION
**Pull request by davehorton**

### CODE REVIEW

**Comment by kitajchuk** [comment]
@davehorton I don’t recall how long the blog link has been around. Does the nav have the right responsive breakpoint to account for the extra link?

**Comment by davehorton** [comment]
hm, good question I don't know.  I will try it on my mobile I guess

**Comment by kitajchuk** [comment]
> hm, good question I don't know. I will try it on my mobile I guess

I’m talking about the interstitial state. So drag from wide to small on desktop and make sure the links don’t break a line before he mobile nav kicks in 🤔

**Comment by davehorton** [comment]
oh yeah, that works.  Looks good to me

https://next-static-site-git-blog-jambonz.vercel.app/

**Review by kitajchuk — APPROVED** [review]

**Pull request merged**
